"""add open_count to entries

Revision ID: 1833dc6b293f
Revises: 924235a09190
Create Date: 2026-07-04 15:33:14.308256
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '1833dc6b293f'
down_revision = '924235a09190'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('open_count', sa.Integer(), server_default='0', nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('open_count')

    # ### end Alembic commands ###
