"""add uuid and deleted_at to entries

Revision ID: 90ded90a513a
Revises: 1833dc6b293f
Create Date: 2026-07-10 21:38:38.083871
"""
from __future__ import annotations

import uuid as uuid_module

import sqlalchemy as sa
from alembic import op

revision = '90ded90a513a'
down_revision = '1833dc6b293f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # uuid must be backfilled for existing rows before it can become NOT
    # NULL + unique, so this happens in three steps instead of the plain
    # autogenerated single add_column(nullable=False).
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    conn = op.get_bind()
    entries = sa.table('entries', sa.column('id', sa.Integer), sa.column('uuid', sa.String))
    for row in conn.execute(sa.select(entries.c.id)):
        conn.execute(
            entries.update()
            .where(entries.c.id == row.id)
            .values(uuid=str(uuid_module.uuid4()))
        )

    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('uuid', nullable=False)
        batch_op.create_index(batch_op.f('ix_entries_uuid'), ['uuid'], unique=True)


def downgrade() -> None:
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_uuid'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('uuid')
