"""add rating_other and year to entries

Revision ID: 924235a09190
Revises: 
Create Date: 2026-07-04 15:11:45.838857
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '924235a09190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_other', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('rating_other')

    # ### end Alembic commands ###
